### ISSUE TITLE
Unable to Load

### ISSUE THREAD

**Issue by joncursi** [matejkriz/react-native-today-widget#8] opened 2017-08-15 07:52 UTC
I am trying to render a verrrry simple today widget but all I get is "Unable to Load". The code uses one View and one Text, and I am running on a simulator in release mode:

```jsx
const TodayWidget = () => (
  <View>

    <Text>
      Hello Today Widget!
    </Text>

  </View>
);
```

**Comment by joncursi** [comment] 2017-08-15 07:54
![screen shot 2017-08-15 at 3 54 14 am](https://user-images.githubusercontent.com/4974609/29306874-6df4b812-816d-11e7-8a1b-f288860039c3.png)

**Comment by matejkriz** [comment] 2017-08-17 14:34
Could you please send the content of Info.plist from the extension?
`node_modules/react-native-today-widget/ios/TodayWidgetExtension/Info.plist`
 At least `CFBundleDisplayName` and `CFBundleIdentifier`.

Also the version of RN could be helpful
`react-native -v`

**Comment by matejkriz** [comment] 2017-08-17 14:46
Running `react-native log-ios` from your project root and then opening the widget could be useful.

**Comment by danik121** [comment] 2017-10-13 12:14
after  react-native log-ios i recieve 
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.DictionaryServiceHelper) <Warning>: Unknown key for Boolean: EnableTransactions
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.DictionaryServiceHelper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnableTransactions
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnableTransactions
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Oct 13 14:13:39 MacBook-Pro-Daniil com.apple.CoreSimulator.SimDevice.0438F0C9-B2C6-49AB-A904-D07178FBE73C[1335] (com.native.userpanel.eroadvertising.TodayWidgetExtension[3681]) <Error>: assertion failed: 17A365: launchd_sim + 63487 [4F755FB1-4156-3577-BEB8-3FD0A54C6323]: 0x16

**Comment by gorohovgame** [comment] 2017-11-02 06:46
I have same issue, any news?

**Comment by matejkriz** [comment] 2017-11-02 08:17
I'm not able to reproduce it. What is your react-native version, please?

**Comment by danik121** [comment] 2017-11-02 08:19
react-native-cli: 2.0.1
react-native: 0.49.

**Comment by gorohovgame** [comment] 2017-11-02 09:19
"react-native": "0.48.4",

**Comment by matejkriz** [comment] 2017-11-02 09:29
Thanks for the info, I will check that again later (I hope this weekend).

**Comment by gorohovgame** [comment] 2017-11-02 09:55
Name and Bundle identifer can change?

**Comment by matejkriz** [comment] 2017-11-02 10:29
Changing the display name for extension is not implemented yet: https://github.com/matejkriz/react-native-today-widget#todo

It's possible only using XCode for now. But those changes are lost on reinstallation of node_modules unfortunately. You could find the Display Name in the `/node_modules/react-native-today-widget/ios/RNTodayWidgetExtension.xcodeproj` project (in the main project it is linked in Libraries) in the TodayWidgetExtension target.

If you change bundle identifier of the main app after installation of react-native-today-widget, you have to 
- reinstall it (`rm -rf node_modules/react-native-today-widget && npm i`) 
- or use bundle-id script (you could find it at `your-main-app-root/node_modules/bundle-id`) or it will work if you add a new npm script to your package.json: `"bundle-id": "bundle-id",` (this script is called automatically on postinstall, that is why the reinstallation could help) 
- or fix it in XCode

I have to add it to the README, thanks for the notice.

**Comment by matejkriz** [comment] 2017-11-03 10:34
@danik121 @gorohovgame It seems to be an issue with XCode 9 https://github.com/wix/detox/issues/352

The original issue from @joncursi had to be something else.

**Comment by matejkriz** [comment] 2017-11-03 15:43
@danik121 @gorohovgame double checked and those warnings really appear only in XCode 9, with XCode 8 it runs without this warnings. But the widget should load anyway (on RN 0.48).

I have to apply the single entry-point change for 0.49 (https://github.com/facebook/react-native/releases/tag/v0.49.0). I don't know how to make it backward compatible, but I plan to release the version for RN 0.49 soon.

**Comment by matejkriz** [comment] 2017-11-03 19:56
Just released v0.8.1 align with RN 0.49. 
@gorohovgame It could still run with RN@0.48.4, but you have to put `AppRegistry.registerComponent('TodayWidgetExtension', () => TodayWidget);` in `index.js` file instead of `index.ios.js`.

**Comment by gorohovgame** [comment] 2017-11-06 19:07
ok! 1 issue fix  index -> index.ios

**Comment by matejkriz** [comment] 2017-11-10 11:01
@gorohovgame I don't know what this error means, but it doesn't block the widget to be rendered.

**Comment by LeVadim** [comment] 2017-12-18 21:04
Hello!

Is there any update regarding this issue?

I am experiencing exactly the same issue with the same error log.
`TodayWidgetExtension[75931]) <Error>: assertion failed: 16G1036: launchd_sim + 63203 []: 0x16`

Thank you!

**Comment by matejkriz** [comment] 2017-12-26 08:54
@LeVadim Could you please provide your result of `react-native info` command? 

Have you tried some super simple widget (something like from the first comment)?

**Comment by kesha-antonov** [comment] 2017-12-30 21:37
Hello!

Same.
Works on simulator.
Does not work on device. Even in release mode.

@matejkriz Have you tried to run ```Complex``` on the device?

**Comment by kesha-antonov** [comment] 2017-12-30 21:49
Seems like my extension uses too much memory:

<img width="778" alt="screen shot 2017-12-31 at 00 49 16" src="https://user-images.githubusercontent.com/11584712/34457536-7b2f26f2-edc4-11e7-919e-0e9d50a0c2e3.png">

**Comment by kesha-antonov** [comment] 2017-12-30 21:57
Sadly I cannot render even simple example:

```
    <View style={{flex: 1}}>
      <Text>
        {'Hello!'}
      </Text>
    </View>
```

**Comment by matejkriz** [comment] 2017-12-31 09:25
Hi @kesha-antonov, could you please provide your result of `react-native info` command? Especially react-native and react versions.

If it works on the simulator and not on the device, it looks like a memory issue. The limit is 16 MB.

It's weird with the simple example. Are you sure, that you run it in release mode? How? Using CLI or XCode? Are you able to run it on the device with Instruments? (attaching the process to Instruments app temporarily disables the memory limits)
Are you running the scheme for your main app or widgets scheme? (the first option is correct, I believe)
To verify the release mode you could use some conditional rendering with `__DEV__` condition as it is for DevMenu in [Complex example](https://github.com/matejkriz/react-native-today-widget/blob/master/Examples/Complex/TodayWidget.js#L15)

The `Complex` example works on my device, but it sometimes crashed on reopening. Click on `Unable to load` always restart it successfully.

![img_4351](https://user-images.githubusercontent.com/3729633/34460598-589c7d98-ee13-11e7-859a-5478e7061aae.JPG)

There is one extra step to run Complex example not described in README yet - manual linking of react-native-fetch-blob to `./node_modules/react-native-today-widget/ios/RNTodayWidgetExtension.xcodeproj` project.

**Comment by kesha-antonov** [comment] 2017-12-31 12:57
Hello again!

react-native info:
```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 6.12.0
  Yarn: 1.3.2
  npm: 5.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0
```

1. ```Are you sure, that you run it in release mode? How? Using CLI or XCode?```

Yes, release mode. Using XCode.

2. ```Are you able to run it on the device with Instruments?```

Yes, it works with Instruments.

3. ```Are you running the scheme for your main app or widgets scheme?```

Main app.

**Comment by matejkriz** [comment] 2017-12-31 13:58
Today widget implementation is great opportunity to learn Swift because it's so simple. But I still hope that I find a way how to save some memory on React Native. JS libraries and HMR are nice benefits. And maybe someday I will add support for Android also...

**Comment by kesha-antonov** [comment] 2018-01-01 12:18
@matejkriz Yes. I agree. ```Learn once, write everywhere``` - as stated in React :)

**Comment by LeVadim** [comment] 2018-01-01 21:28
Dear members!
 I agree about involving Swift into this process.
How would you access AsyncStorage from the Today Widget written in Swift?

Thank you!

**Comment by matejkriz** [comment] 2018-01-08 20:51
@LeVadim For reading `AsyncStorage` from native code you could try import `RCTAsyncLocalStorage.h` and call` _getValueForKey:`: https://stackoverflow.com/a/34515562/7414186

But I believe there is no way to share AsyncStorage between main app and the widget. You have to put the widget and main app into App Group and use native `UserDefaults` (for UserDefaults  from React Native you could use https://facebook.github.io/react-native/docs/settings.html).

**Comment by LeVadim** [comment] 2018-01-08 20:53
Dear Matěj!
Thank you for getting back, that`s exactly what I did!
Custom OBJ-C for react native side + widget written in swift with shared group worked very well.
Thank you!

**Comment by mirkods** [comment] 2018-01-10 10:41
Hi everyone,
I'm having the same issue with this versions:
```
"react": "16.0.0",
"react-native": "^0.50.3"
```

Basically my app is very simple, just one listview that fetch data from an api anche show them so I don't think that could be a too memory issue.
How can I solve? I'm not able to write the widget using Swift right know so I'd like to do this on JS side.

Mirko

**Comment by matejkriz** [comment] 2018-01-13 18:51
Hi @mirkods, if you believe it's not a memory issue (you could verify it in Instruments app), try to check the logs. 

To see logs from native, run this command:
`react-native log-ios`

To debug JS, add this to your main component:
```
import { NativeModules } from 'react-native';
NativeModules.DevSettings.setIsDebuggingRemotely(true);
```

**Comment by mirkods** [comment] 2018-01-22 13:29
Hi @matejkriz can you please tell me the steps to verify with the Instrument app that is not a memory issue?

These are my logs after the command `react-native log-ios`:
```
n 22 14:27:31 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd[11229]) <Warning>: Service exited with abnormal code: 1
Jan 22 14:27:31 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 22 14:27:37 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.mirko.Arbitrage.TodayWidgetExtension) <Warning>: Unknown key for Boolean: EnableTransactions
Jan 22 14:27:37 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.mirko.Arbitrage.TodayWidgetExtension) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jan 22 14:27:38 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnableTransactions
Jan 22 14:27:38 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jan 22 14:27:38 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnableTransactions
Jan 22 14:27:38 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jan 22 14:27:38 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.mirko.Arbitrage.TodayWidgetExtension[11231]) <Error>: assertion failed: 17C205: launchd_sim + 63203 [73626DE2-C6D1-3394-9991-3E928BFE8F25]: 0x16
Jan 22 14:27:41 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd[11234]) <Warning>: Service exited with abnormal code: 1
Jan 22 14:27:41 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 22 14:27:51 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd[11236]) <Warning>: Service exited with abnormal code: 1
Jan 22 14:27:51 user com.apple.CoreSimulator.SimDevice.D4049623-5004-4E85-9549-F2719CF30FFB[10628] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

What you think about these logs?

**Comment by simonemarinelli** [comment] 2018-02-08 11:51
Same issue.

```
> react-native-info

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.9.2
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3871768

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2
```

**Comment by YusufBesim** [comment] 2018-03-05 09:29
Same here! in release mode not working to. "Unable to load"

**Comment by MaxToyberman** [comment] 2018-06-03 06:45
Hi, please view my pr , I have manage to solve this problem 
https://github.com/matejkriz/react-native-today-widget/pull/19
you can also read my blog about this
https://medium.com/@maximtoyberman/building-a-react-native-today-widget-in-ios-102830825e42

**Comment by MaxToyberman** [comment] 2018-06-03 06:46
it is wrong to use the same index.js both for the app and widget

**Comment by matejkriz** [comment] 2018-06-03 09:57
Wow, that's awesome! Thanks, @MaxToyberman, you are the first contributor! :tada: 

I'm going to review it and test it. I thought, that it is problem with bundling, but didn't think the solution would be so simple. I was experimenting with unbundling 
https://facebook.github.io/react-native/docs/performance.html#unbundling-inline-requires

**Comment by matejkriz** [comment] 2018-06-03 13:42
PR #19 from @MaxToyberman merged, new version `1.0.0` released.

**Closed by matejkriz** 2018-06-03 13:42 UTC
Labels: bug

**Comment by MaxToyberman** [comment] 2018-06-04 08:27
@matejkriz  This is working perfectly :) please check it and let me know.

**Comment by munsifhayat** [comment] 2019-03-14 07:32
@MaxToyberman  Thanks for the very helpful blog. I followed your recommendations but somehow not able to run it on Actual device. On Simulator it is working perfectly fine.
