### ISSUE TITLE
Error: Bundle identifier

### ISSUE THREAD

**Issue by 007agentHP** [matejkriz/react-native-today-widget#7] opened 2017-08-15 06:16 UTC
while attempting to run my app, it reached the following build error:

`The following build commands failed:
	ValidateEmbeddedBinary build/Build/Products/Debug-iphonesimulator/WidgetTest.app/PlugIns/TodayWidgetExtension.appex
(1 failure)`

and above it listed this:

`error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	.TodayWidgetExtension
		Parent App Bundle Identifier:		org.reactjs.native.example.WidgetTest`

i installed all the dependencies and multiple tests yielded the same error.
am i doing anything wrong? i copy-pasted the widget code from the example and it still doesnt work.

**Comment by matejkriz** [comment] 2017-08-17 14:05
@007agentHP What is your version of npm/yarn, please?
`npm --version` or `yarn --version`

It is problem with `bundle-id` script running in postinstall phase. Could you please try reinstall the library and post any error you get?
`npm uninstall react-native-today-widget && npm i react-native-today-widget`

For manual fixing your issue, you could set proper bundle identifier manually in
`./node_modules/react-native-today-widget/ios/TodayWidgetExtension/Info.plist`
Change the string for `CFBundleIdentifier` key to `org.reactjs.native.example.WidgetTest.TodayWidgetExtension`.

Or in XCode:
<img width="1280" alt="extensions-bundle-id" src="https://user-images.githubusercontent.com/3729633/29416187-a28af27c-8365-11e7-9aa7-d9b5d8bd365d.png">

**Comment by matejkriz** [comment] 2017-09-10 14:43
Should be fixed in [0.7.1](https://github.com/matejkriz/react-native-today-widget/releases/tag/v0.7.1)

Please retest it with new version and reopen this issue if the problem is still there.

**Closed by matejkriz** 2017-09-10 14:43 UTC
